const mongoose = require('mongoose');

const agentEventSchema = new mongoose.Schema(
  {
    eventId: {
      type: String,
      default: () => `EVT-${Date.now()}-${Math.floor(Math.random() * 10000)}`,
    },
    type: {
      type: String,
      enum: [
        'RECOVERY_STARTED',
        'OBSERVATION_CREATED',
        'STRATEGY_SELECTED',
        'DECISION_MADE',
        'TOOL_STARTED',
        'TOOL_COMPLETED',
        'TOOL_FAILED',
        'FALLBACK_TRIGGERED',
        'PROVIDER_SWITCHED',
        'PLAN_CREATED',
        'PLAN_EVALUATED',
        'PLAN_REJECTED',
        'PLAN_SELECTED',
        'FAILURE_DETECTED',
        'ADAPTATION_TRIGGERED',
        'RISK_UPDATED',
        'IMPACT_DETECTED',
        'PLAN_VERIFIED',
        'RECOVERY_PLAN_READY',
        'AWAITING_APPROVAL',
        'RECOVERY_COMPLETED',
        'RECOVERY_FAILED',
        'MAX_ITERATIONS_REACHED',
        'SIMULATION_STARTED',
        'SIMULATION_COMPLETED',
        'REPLAN_TRIGGERED',
        'STATE_UPDATED',
        // Phase 4 — LLM Agent events
        'LLM_STARTED',
        'LLM_COMPLETED',
        'LLM_FAILED',
        'LLM_FALLBACK',
        'LLM_DECISION',
        'LLM_DECISION_REJECTED',
        // Phase 5 — External Handoff events
        'HANDOFF_APPROVED',
        'EXTERNAL_HANDOFF',
        'HANDOFF_FAILED',
        // Phase 11 — Notifications & Calendar events
        'DISRUPTION_DETECTED',
        'CONNECTION_AT_RISK',
        'PLAN_INVALIDATED',
        'APPROVAL_REQUIRED',
        'RECOVERY_UPDATED',
        'INSURANCE_REVIEW_READY',
        'COMPENSATION_REVIEW_READY',
        'CALENDAR_CONFLICT',
        'CALENDAR_UPDATED',
        'NOTIFICATION_CREATED',
        // Phase 14 — Monitoring events
        'MONITORING_CHECKED',
        'MONITORING_ALERT',
        'FLIGHT_DELAYED',
        'FLIGHT_CANCELLED',
        'TRAIN_DELAYED',
        'TRAIN_CANCELLED',
        'BUS_DELAYED',
        'BUS_CANCELLED',
        'HOTEL_CHANGED',
        'PRICE_CHANGED',
        'AVAILABILITY_CHANGED',
      ],
    },
    timestamp: { type: Date, default: Date.now },
    message: { type: String, default: '' },
    strategy: { type: String, default: null },
    iteration: { type: Number, default: 0 },
    metadata: { type: mongoose.Schema.Types.Mixed, default: null },
  },
  { _id: false }
);

module.exports = agentEventSchema;
